TOGGLE_PAUSE = 0;
paused_ = false;
score = 0;
global.key_revert	= ord("X");
global.key_enter	= vk_enter;
global.key_left		= ord("A");
global.key_right	= ord("D");
global.key_up		= ord("W");
global.key_down		= ord("S");
draw_set_font(f_one);
global.P_System=part_system_create_layer("instances", true);
global.view_width	= camera_get_view_width(view_camera[0]);
global.view_height	= camera_get_view_height(view_camera[0]);
display_set_gui_size(global.view_width	, global.view_height);