global.Particle1 = part_type_create();
part_type_shape(global.Particle1, pt_shape_flare);
part_type_size(global.Particle1, 0.01, 0.05, 0, 0.5);
part_type_color3(global.Particle1, c_aqua, c_blue, c_blue);
part_type_speed(global.Particle1, 0,0,0,0);
part_type_direction(global.Particle1, -1, 1, 0, 0);
part_type_blend(global.Particle1, true);
part_type_life(global.Particle1, 5, 20);
global.Particle2 = part_type_create();
part_type_shape(global.Particle2, pt_shape_flare);
part_type_size(global.Particle2, 0.01, 0.1, 0, 0.5);
part_type_color3(global.Particle2, c_red, c_red, c_red);
part_type_speed(global.Particle2, 0,0,0,0);
part_type_direction(global.Particle2, 0, 0, 0, 20);
part_type_blend(global.Particle2, false);
part_type_life(global.Particle2, 5, 20);
global.Particle3 = part_type_create();
part_type_shape(global.Particle3, pt_shape_flare);
part_type_size(global.Particle3, 0.01, 0.05, 0, 0.5);
part_type_color3(global.Particle3, c_red, c_orange, c_red);
part_type_speed(global.Particle3, 0,1,0.1,0);
part_type_direction(global.Particle3, 0, 360, 0, 20);
part_type_blend(global.Particle3, true);
part_type_life(global.Particle3, 30, 60);
global.Particle4 = part_type_create();
part_type_shape(global.Particle4, pt_shape_square);
part_type_size(global.Particle4, 0.01, 0.05, 0.01, 0);
part_type_color1(global.Particle4, c_orange);
part_type_alpha1(global.Particle4, 1);
part_type_speed(global.Particle4, 0,0.5,0.1,0);
part_type_direction(global.Particle4, 0, 360, 0,3);
part_type_blend(global.Particle4, true);
part_type_life(global.Particle4, 20, 40);
global.Particle5 = part_type_create();
part_type_shape(global.Particle5, pt_shape_flare);
part_type_size(global.Particle5, 0.01, 0.05, 0, 0.5);
part_type_color3(global.Particle5, c_yellow, c_orange, c_yellow);
part_type_alpha3(global.Particle5, 0.7, 1, 0.2);
part_type_speed(global.Particle5, 0,0,0,0);
part_type_direction(global.Particle5, -1, 1, 0, 0);
part_type_blend(global.Particle5, true);
part_type_life(global.Particle5, 10, 30);
global.Particle6 = part_type_create();
part_type_shape(global.Particle6, pt_shape_flare);
part_type_size(global.Particle6, 0.01, 0.05, 0, 0.5);
part_type_color1(global.Particle6, c_green);
part_type_alpha3(global.Particle6, 0.7, 1, 0.2);
part_type_speed(global.Particle6, 0,0,0,0);
part_type_direction(global.Particle6, -1, 1, 0, 0);
part_type_blend(global.Particle6, true);
part_type_life(global.Particle6, 10, 30);
global.Particle7 = part_type_create();
part_type_shape(global.Particle7, pt_shape_flare);
part_type_size(global.Particle7, 0.01, 0.05, 0, 0.5);
part_type_color1(global.Particle7, c_fuchsia);
part_type_alpha3(global.Particle7, 0.7, 1, 0.2);
part_type_speed(global.Particle7, 0,0,0,0);
part_type_direction(global.Particle7, -1, 1, 0, 0);
part_type_blend(global.Particle7, true);
part_type_life(global.Particle7, 10, 30);
global.Particle8 = part_type_create();
part_type_shape(global.Particle8, pt_shape_flare);
part_type_size(global.Particle8, 0.01, 0.05, 0, 0.5);
part_type_color1(global.Particle8, c_dkgray);
part_type_alpha3(global.Particle8, 0.7, 1, 0.2);
part_type_speed(global.Particle8, 0,0,0,0);
part_type_direction(global.Particle8, -1, 1, 0, 0);
part_type_blend(global.Particle8, false);
part_type_life(global.Particle8, 10, 30);
global.Particle9 = part_type_create();
part_type_shape(global.Particle9, pt_shape_flare);
part_type_size(global.Particle9, 0.01, 0.05, 0, 0.5);
part_type_color1(global.Particle9, c_aqua);
part_type_speed(global.Particle9, 0,0,0,0);
part_type_direction(global.Particle9, -1, 1, 0, 0);
part_type_blend(global.Particle9, false);
part_type_life(global.Particle9, 10, 30);
global.Particle10 = part_type_create();
part_type_shape(global.Particle10, pt_shape_smoke);
part_type_size(global.Particle10, 0.01, 0.05, 0, 0.5);
part_type_color1(global.Particle10, c_purple);
part_type_speed(global.Particle10, 0,0,0,0);
part_type_direction(global.Particle10, -1, 1, 0, 0);
part_type_blend(global.Particle10, true);
part_type_life(global.Particle10, 10, 30);
global.Particle11 = part_type_create();
part_type_shape(global.Particle11, pt_shape_smoke);
part_type_size(global.Particle11, 0.01, 0.05, 0, 0.5);
part_type_color3(global.Particle11, c_red,c_orange,c_yellow);
part_type_speed(global.Particle11, 0,0,0,0);
part_type_direction(global.Particle11, -1, 1, 0, 0);
part_type_blend(global.Particle11, true);
part_type_life(global.Particle11, 10, 30);
room_persistent = true
